[package]
name = "lockdock-mouse"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
build = "build.rs"

[dependencies]
thiserror.workspace = true
lockdock-geometry.workspace = true

[build-dependencies]
cc.workspace = true

[lints]
workspace = true
