[package]
name = "lockdock-daemon"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
lockdock-display = { path = "../lockdock-display" }
lockdock-ipc = { path = "../lockdock-ipc" }
prefs.workspace = true
thiserror.workspace = true

[lints.rust]
unreachable_pub = "warn"

[lints.clippy]
pedantic = { level = "warn", priority = -2 }
missing_errors_doc = "allow"
module_name_repetitions = "allow"
too_many_lines = "allow"
