name: Quality Assurance

on:
    pull_request:
    push:

permissions:
    contents: read

env:
    LLVM_VERSION: 22

jobs:
    lint:
        name: Lint
        runs-on: macos-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v6.0.2

            - name: Setup LLVM
              run: |
                  brew install llvm@${{ env.LLVM_VERSION }}
                  echo "$(brew --prefix llvm@${{ env.LLVM_VERSION }})/bin/" >> $GITHUB_PATH

            - name: Check code quality
              run: |
                  export PATH=$(brew --prefix llvm@20)/bin/:$PATH
                  make tidy

    test:
        name: Test
        strategy:
            matrix:
                runner: [macos-26-intel, macos-26]
        runs-on: ${{ matrix.runner }}

        steps:
            - name: Checkout
              uses: actions/checkout@v6.0.2

            - name: Setup LLVM
              run: |
                  brew install llvm@${{ env.LLVM_VERSION }}
                  echo "$(brew --prefix llvm@${{ env.LLVM_VERSION }})/bin/" >> $GITHUB_PATH

            - name: Test
              run: make test
