name: Quality Assurance

on:
    pull_request:
    push:

permissions:
    contents: read

jobs:
    lint:
        name: Lint
        runs-on: macos-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v7

            - name: Setup Rust
              uses: actions-rust-lang/setup-rust-toolchain@v1
              with:
                  components: rustfmt, clippy

            - name: Check code quality
              run: make lint

    test:
        name: Test
        strategy:
            matrix:
                runner: [macos-26-intel, macos-26]
        runs-on: ${{ matrix.runner }}

        steps:
            - name: Checkout
              uses: actions/checkout@v7

            - name: Setup Rust
              uses: actions-rust-lang/setup-rust-toolchain@v1
              with:
                  components: rustfmt, clippy

            - name: Test
              run: make test
